#!/bin/sh
## kc3
## Copyright from 2022 to 2026 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

TEST_NAME=http

SRC_TOP="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

cd "${SRC_TOP}/test/${TEST_NAME}" || exit

. ../test.subr

if [ $# = 0 ]; then
    if [ "x${HTTP_TEST}" = "x" ]; then
        TARGETS="$(ls -1 *.kc3 | sed -e 's/[.]kc3$//')"
    else
        TARGETS="$(echo "${HTTP_TEST}" | tr ' ' '\n')"
    fi
else
    TARGETS="$(echo "$@" | tr ' ' '\n')"
fi

test_run "$IKC3" $TARGETS
