#!/bin/sh
## kc3
## Copyright from 2022 to 2025 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

cd "$(dirname $0)/ikc3" || exit

. ../test.subr

if [ $# = 0 ]; then
    if [ "x${IKC3_TEST}" = "x" ]; then
        TARGETS="$(ls -1 *.kc3 | sed -e 's/[.]kc3$//')"
        case "$IKC3" in
            *_asan)
                TARGETS="$(echo "${TARGETS}" |
                                grep -E -v -e '^block$' \
                                           -e '^unwind_protect$' \
                                           -e '^while$')"
                ;;
            *)
                ;;
        esac
    else
        TARGETS="$(echo "${IKC3_TEST}" | tr ' ' '\n')"
    fi
else
    TARGETS="$(echo "$@" | tr ' ' '\n')"
fi

rm -f *.diff *.out *.ret
rm -f .test .test_ko .test_ok
touch .test .test_ko .test_ok
for TARGET in $TARGETS; do
    echo "( ../ikc3_test_target $TARGET; )"
done | runj -1 /bin/sh

TEST_COUNT=$(echo $(wc -l .test) | cut -f 1 -d ' ')
TEST_KO=$(echo $(wc -l .test_ko) | cut -f 1 -d ' ')
TEST_OK=$(echo $(wc -l .test_ok) | cut -f 1 -d ' ')
echo
DIFFS="$(for TARGET in $TARGETS; do
    if [ -f "${TARGET}.diff" ]; then
        printf "%s " "${TARGET}.diff"
    fi
done)"
if [ "x$DIFFS" != "x" ]; then
    ls $DIFFS
    less $DIFFS || cat $DIFFS
fi
echo
printf "%s" "Total $TEST_COUNT tests. "
printf "%s" "${TEST_COLOR_OK}OK $TEST_OK ($(($TEST_OK * 100 / $TEST_COUNT))%)${TEST_COLOR_RESET}. "
echo "${TEST_COLOR_KO}KO $TEST_KO ($(($TEST_KO * 100 / $TEST_COUNT))%)${TEST_COLOR_RESET}."

if [ "x$TEST_KO" = "x0" ]; then
    exit 0
fi

exit 1
