#!/bin/sh
## kc3
## Copyright from 2022 to 2026 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

TEST_NAME=socket

TEST_TOP="$(cd "$(dirname "$0")" && pwd)"

cd "${TEST_TOP}/${TEST_NAME}" || exit

. ../test.subr

if [ $# = 0 ]; then
    if [ "x${SOCKET_TEST}" = "x" ]; then
        TARGETS="$(ls -1 *.kc3 | sed -e 's/[.]kc3$//')"
    else
        TARGETS="$(echo "${IKC3_TEST}" | tr ' ' '\n')"
    fi
else
    TARGETS="$(echo "$@" | tr ' ' '\n')"
fi

: ${KC3S=${TEST_TOP}/../kc3s/kc3s}

test_run "$KC3S" $TARGETS
