# sources.mk generated by update_sources
HEADERS = \
	"buf_parse_test.h" \
	"buf_parse_test_su.h" \
	"compare_test.h" \
	"fact_test.h" \
	"tag_test.h" \
	"test.h" \

SOURCES = \
	"array_test.c" \
	"bool_test.c" \
	"buf_file_test.c" \
	"buf_inspect_test.c" \
	"buf_parse_test.c" \
	"buf_parse_test_s16.c" \
	"buf_parse_test_s32.c" \
	"buf_parse_test_s64.c" \
	"buf_parse_test_s8.c" \
	"buf_parse_test_u16.c" \
	"buf_parse_test_u32.c" \
	"buf_parse_test_u64.c" \
	"buf_parse_test_u8.c" \
	"buf_test.c" \
	"call_test.c" \
	"cfn_test.c" \
	"character_test.c" \
	"compare_test.c" \
	"env_test.c" \
	"fact_test.c" \
	"facts_cursor_test.c" \
	"facts_test.c" \
	"facts_with_test.c" \
	"fn_test.c" \
	"hash_test.c" \
	"ident_test.c" \
	"libkc3_test.c" \
	"list_test.c" \
	"ratio_test.c" \
	"set__fact_test.c" \
	"set__tag_test.c" \
	"skiplist__fact_test.c" \
	"str_test.c" \
	"sym_test.c" \
	"tag_test.c" \
	"test.c" \
	"tuple_test.c" \
	"types_test.c" \

