#!/bin/sh
## kc3
## Copyright from 2022 to 2025 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

TEST_COLOR_KO="[0;91m"
TEST_COLOR_OK="[0;92m"
TEST_COLOR_RESET="[0m"
TEST_COUNT=0
TEST_KO=0
TEST_OK=0

if [ "x$IKC3" = "x" ]; then
    if [ -f ../../ikc3/ikc3 ]; then
	IKC3=../../ikc3/ikc3
    elif [ -f ../../ikc3 ]; then
	IKC3=../../ikc3
    fi
fi

test_ko() {
    printf "%s" "${TEST_COLOR_KO}F${TEST_COLOR_RESET}"
    echo $@ >> .test_ko
    echo $@ >> .test
}

test_ok() {
    printf "%s" "${TEST_COLOR_OK}.${TEST_COLOR_RESET}"
    echo $@ >> .test_ok
    echo $@ >> .test
}
