# sources.sh generated by update_sources
HEADERS='bg_rect.h earth.h flies.h lightspeed.h mandelbrot_f128.h matrix.h toasters.h window_egl_demo.h '
SOURCES='bg_rect.c earth.c flies.c lightspeed.c mandelbrot_f128.c matrix.c toasters.c '
