# sources.mk generated by update_sources
HEADERS = \
	"blob.h" \
	"branch.h" \
	"files.h" \
	"git.h" \
	"log.h" \
	"reference.h" \
	"repository.h" \
	"tag.h" \

SOURCES = \
	"blob.c" \
	"branch.c" \
	"files.c" \
	"log.c" \
	"reference.c" \
	"repository.c" \
	"tag.c" \

