# sources.mk generated by update_sources
HEADERS = \
	"pdf.h" \
	"pdf_buf_parse.h" \
	"pdf_file.h" \
	"pdf_name.h" \
	"pdf_trailer.h" \
	"pdf_write.h" \
	"types.h" \

SOURCES = \
	"pdf.c" \
	"pdf_buf_parse.c" \
	"pdf_file.c" \
	"pdf_name.c" \
	"pdf_trailer.c" \
	"pdf_write.c" \

