# sources.sh generated by update_sources
HEADERS='pdf.h pdf_buf_parse.h pdf_buf_write.h pdf_file.h pdf_name.h pdf_stream.h pdf_trailer.h types.h '
SOURCES='pdf.c pdf_buf_parse.c pdf_buf_write.c pdf_file.c pdf_name.c pdf_stream.c pdf_trailer.c '
