# sources.mk generated by update_sources
HEADERS = \
	"quartz_to_xkbcommon.h" \
	"window_cairo_quartz.h" \
	"window_cairo_quartz_app_delegate.h" \
	"window_cairo_quartz_view.h" \
	"window_cairo_quartz_view_controller.h" \

SOURCES = \
	"quartz_to_xkbcommon.c" \

OBJC_SOURCES = \
	"window_cairo_quartz.m" \
	"window_cairo_quartz_app_delegate.m" \
	"window_cairo_quartz_view.m" \
	"window_cairo_quartz_view_controller.m" \

