# sources.sh generated by update_sources
HEADERS='bg_rect.h flies.h lightspeed.h mandelbrot_f128.h toasters.h window_cairo_demo.h '
SOURCES='bg_rect.c flies.c lightspeed.c mandelbrot_f128.c toasters.c window_cairo_demo.c '
