# sources.mk generated by update_sources
HEADERS = \
	"gl_deprecated.h" \
	"gl_font.h" \
	"gl_object.h" \
	"gl_ortho.h" \
	"gl_square.h" \
	"gl_text.h" \
	"gl_triangle.h" \
	"gl_vertex.h" \
	"mat4.h" \
	"sequence.h" \
	"types.h" \
	"vec3.h" \
	"window_egl.h" \

SOURCES = \
	"gl_deprecated.c" \
	"gl_font.c" \
	"gl_object.c" \
	"gl_ortho.c" \
	"gl_square.c" \
	"gl_text.c" \
	"gl_triangle.c" \
	"gl_vertex.c" \
	"mat4.c" \
	"sequence.c" \
	"vec3.c" \
	"window_egl.c" \

OBJC_SOURCES = \
	"" \

