# sources.sh generated by update_sources
HEADERS='http.h http_event.h http_request.h http_response.h mime_type.h socket.h socket_addr.h socket_buf.h types.h '
SOURCES='http.c http_event.c http_request.c http_response.c mime_type.c socket.c socket_addr.c socket_buf.c '
