# sources.sh generated by update_sources
HEADERS='bg_rect.h earth.h flies.h lightspeed.h mandelbrot_f128.h matrix_utf8.h toasters.h window_sdl2_demo.h '
SOURCES='bg_rect.c earth.c flies.c lightspeed.c mandelbrot_f128.c matrix_utf8.c toasters.c window_sdl2_demo.c '
