# sources.sh generated by update_sources
HEADERS='bg_rect.h earth.h flies.h lightspeed.h toasters.h window_sdl2_demo.h '
SOURCES='bg_rect.c earth.c flies.c lightspeed.c toasters.c window_sdl2_demo.c '
