# sources.mk generated by update_sources
SOURCES = buf_linenoise.c ic3.c linenoise.c 

buf_linenoise.lo: buf_linenoise.c /usr/include/assert.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/err.h /usr/include/machine/_types.h /usr/include/stdio.h \
  /usr/include/sys/_null.h /usr/include/sys/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  /usr/include/stdlib.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h ../libc3/c3.h \
  ../libc3/arg.h ../libc3/types.h /usr/include/limits.h \
  /usr/include/sys/limits.h /usr/include/machine/limits.h \
  /usr/include/sys/syslimits.h /usr/include/setjmp.h \
  /usr/include/machine/setjmp.h ../libc3/../libtommath/tommath.h \
  /usr/include/stdint.h /usr/include/stddef.h ../libc3/bool.h \
  ../libc3/hash.h /usr/include/sha1.h ../libc3/buf.h \
  /usr/include/stdarg.h ../libc3/buf_file.h ../libc3/buf_inspect.h \
  ../libc3/buf_parse.h ../libc3/buf_save.h ../libc3/call.h \
  ../libc3/character.h ../libc3/debug.h ../libc3/env.h ../libc3/eval.h \
  ../libc3/f32.h ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h \
  ../libc3/fn.h ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h \
  ../libc3/list.h ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h \
  ../libc3/s8.h ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h \
  ../libc3/str.h ../libc3/tag.h ../libc3/../libffi/ffi.h \
  ../libc3/../libffi/ffitarget.h ../libc3/tuple.h ../libc3/u8.h \
  ../libc3/u16.h ../libc3/u32.h ../libc3/u64.h ../libc3/ucd.h \
  ../libc3/../ucd2c/ucd.h ../linenoise/linenoise.h
buf_linenoise.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS} -c buf_linenoise.c -o buf_linenoise.lo

buf_linenoise.asan.lo: buf_linenoise.c /usr/include/assert.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/err.h /usr/include/machine/_types.h /usr/include/stdio.h \
  /usr/include/sys/_null.h /usr/include/sys/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  /usr/include/stdlib.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h ../libc3/c3.h \
  ../libc3/arg.h ../libc3/types.h /usr/include/limits.h \
  /usr/include/sys/limits.h /usr/include/machine/limits.h \
  /usr/include/sys/syslimits.h /usr/include/setjmp.h \
  /usr/include/machine/setjmp.h ../libc3/../libtommath/tommath.h \
  /usr/include/stdint.h /usr/include/stddef.h ../libc3/bool.h \
  ../libc3/hash.h /usr/include/sha1.h ../libc3/buf.h \
  /usr/include/stdarg.h ../libc3/buf_file.h ../libc3/buf_inspect.h \
  ../libc3/buf_parse.h ../libc3/buf_save.h ../libc3/call.h \
  ../libc3/character.h ../libc3/debug.h ../libc3/env.h ../libc3/eval.h \
  ../libc3/f32.h ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h \
  ../libc3/fn.h ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h \
  ../libc3/list.h ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h \
  ../libc3/s8.h ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h \
  ../libc3/str.h ../libc3/tag.h ../libc3/../libffi/ffi.h \
  ../libc3/../libffi/ffitarget.h ../libc3/tuple.h ../libc3/u8.h \
  ../libc3/u16.h ../libc3/u32.h ../libc3/u64.h ../libc3/ucd.h \
  ../libc3/../ucd2c/ucd.h ../linenoise/linenoise.h
buf_linenoise.asan.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_ASAN} -c buf_linenoise.c -o buf_linenoise.asan.lo

buf_linenoise.debug.lo: buf_linenoise.c /usr/include/assert.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/err.h /usr/include/machine/_types.h /usr/include/stdio.h \
  /usr/include/sys/_null.h /usr/include/sys/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  /usr/include/stdlib.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h ../libc3/c3.h \
  ../libc3/arg.h ../libc3/types.h /usr/include/limits.h \
  /usr/include/sys/limits.h /usr/include/machine/limits.h \
  /usr/include/sys/syslimits.h /usr/include/setjmp.h \
  /usr/include/machine/setjmp.h ../libc3/../libtommath/tommath.h \
  /usr/include/stdint.h /usr/include/stddef.h ../libc3/bool.h \
  ../libc3/hash.h /usr/include/sha1.h ../libc3/buf.h \
  /usr/include/stdarg.h ../libc3/buf_file.h ../libc3/buf_inspect.h \
  ../libc3/buf_parse.h ../libc3/buf_save.h ../libc3/call.h \
  ../libc3/character.h ../libc3/debug.h ../libc3/env.h ../libc3/eval.h \
  ../libc3/f32.h ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h \
  ../libc3/fn.h ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h \
  ../libc3/list.h ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h \
  ../libc3/s8.h ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h \
  ../libc3/str.h ../libc3/tag.h ../libc3/../libffi/ffi.h \
  ../libc3/../libffi/ffitarget.h ../libc3/tuple.h ../libc3/u8.h \
  ../libc3/u16.h ../libc3/u32.h ../libc3/u64.h ../libc3/ucd.h \
  ../libc3/../ucd2c/ucd.h ../linenoise/linenoise.h
buf_linenoise.debug.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_DEBUG} -c buf_linenoise.c -o buf_linenoise.debug.lo

ic3.lo: ic3.c ../libc3/c3.h ../libc3/arg.h ../libc3/types.h \
  /usr/include/limits.h /usr/include/sys/cdefs.h \
  /usr/include/machine/cdefs.h /usr/include/sys/limits.h \
  /usr/include/machine/limits.h /usr/include/sys/syslimits.h \
  /usr/include/setjmp.h /usr/include/machine/setjmp.h \
  /usr/include/stdio.h /usr/include/sys/_null.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  ../libc3/../libtommath/tommath.h /usr/include/stdint.h \
  /usr/include/stddef.h ../libc3/bool.h ../libc3/hash.h \
  /usr/include/sha1.h ../libc3/buf.h /usr/include/assert.h \
  /usr/include/err.h /usr/include/stdarg.h /usr/include/stdlib.h \
  ../libc3/buf_file.h ../libc3/buf_inspect.h ../libc3/buf_parse.h \
  ../libc3/buf_save.h ../libc3/call.h ../libc3/character.h \
  ../libc3/debug.h ../libc3/env.h ../libc3/eval.h ../libc3/f32.h \
  ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h ../libc3/fn.h \
  ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h ../libc3/list.h \
  ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h ../libc3/s8.h \
  ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h ../libc3/str.h \
  ../libc3/tag.h ../libc3/../libffi/ffi.h ../libc3/../libffi/ffitarget.h \
  ../libc3/tuple.h ../libc3/u8.h ../libc3/u16.h ../libc3/u32.h \
  ../libc3/u64.h ../libc3/ucd.h ../libc3/../ucd2c/ucd.h buf_linenoise.h
ic3.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS} -c ic3.c -o ic3.lo

ic3.asan.lo: ic3.c ../libc3/c3.h ../libc3/arg.h ../libc3/types.h \
  /usr/include/limits.h /usr/include/sys/cdefs.h \
  /usr/include/machine/cdefs.h /usr/include/sys/limits.h \
  /usr/include/machine/limits.h /usr/include/sys/syslimits.h \
  /usr/include/setjmp.h /usr/include/machine/setjmp.h \
  /usr/include/stdio.h /usr/include/sys/_null.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  ../libc3/../libtommath/tommath.h /usr/include/stdint.h \
  /usr/include/stddef.h ../libc3/bool.h ../libc3/hash.h \
  /usr/include/sha1.h ../libc3/buf.h /usr/include/assert.h \
  /usr/include/err.h /usr/include/stdarg.h /usr/include/stdlib.h \
  ../libc3/buf_file.h ../libc3/buf_inspect.h ../libc3/buf_parse.h \
  ../libc3/buf_save.h ../libc3/call.h ../libc3/character.h \
  ../libc3/debug.h ../libc3/env.h ../libc3/eval.h ../libc3/f32.h \
  ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h ../libc3/fn.h \
  ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h ../libc3/list.h \
  ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h ../libc3/s8.h \
  ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h ../libc3/str.h \
  ../libc3/tag.h ../libc3/../libffi/ffi.h ../libc3/../libffi/ffitarget.h \
  ../libc3/tuple.h ../libc3/u8.h ../libc3/u16.h ../libc3/u32.h \
  ../libc3/u64.h ../libc3/ucd.h ../libc3/../ucd2c/ucd.h buf_linenoise.h
ic3.asan.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_ASAN} -c ic3.c -o ic3.asan.lo

ic3.debug.lo: ic3.c ../libc3/c3.h ../libc3/arg.h ../libc3/types.h \
  /usr/include/limits.h /usr/include/sys/cdefs.h \
  /usr/include/machine/cdefs.h /usr/include/sys/limits.h \
  /usr/include/machine/limits.h /usr/include/sys/syslimits.h \
  /usr/include/setjmp.h /usr/include/machine/setjmp.h \
  /usr/include/stdio.h /usr/include/sys/_null.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/types.h /usr/include/sys/endian.h \
  /usr/include/sys/_endian.h /usr/include/machine/endian.h \
  ../libc3/../libtommath/tommath.h /usr/include/stdint.h \
  /usr/include/stddef.h ../libc3/bool.h ../libc3/hash.h \
  /usr/include/sha1.h ../libc3/buf.h /usr/include/assert.h \
  /usr/include/err.h /usr/include/stdarg.h /usr/include/stdlib.h \
  ../libc3/buf_file.h ../libc3/buf_inspect.h ../libc3/buf_parse.h \
  ../libc3/buf_save.h ../libc3/call.h ../libc3/character.h \
  ../libc3/debug.h ../libc3/env.h ../libc3/eval.h ../libc3/f32.h \
  ../libc3/f64.h ../libc3/fact.h ../libc3/facts.h ../libc3/fn.h \
  ../libc3/ident.h ../libc3/sym.h ../libc3/integer.h ../libc3/list.h \
  ../libc3/ptag.h ../libc3/ptr.h ../libc3/quote.h ../libc3/s8.h \
  ../libc3/s16.h ../libc3/s32.h ../libc3/s64.h ../libc3/str.h \
  ../libc3/tag.h ../libc3/../libffi/ffi.h ../libc3/../libffi/ffitarget.h \
  ../libc3/tuple.h ../libc3/u8.h ../libc3/u16.h ../libc3/u32.h \
  ../libc3/u64.h ../libc3/ucd.h ../libc3/../ucd2c/ucd.h buf_linenoise.h
ic3.debug.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_DEBUG} -c ic3.c -o ic3.debug.lo

linenoise.lo: linenoise.c ../linenoise/linenoise.c /usr/include/termios.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/ttycom.h /usr/include/sys/ioccom.h \
  /usr/include/sys/ttydefaults.h /usr/include/unistd.h \
  /usr/include/sys/_null.h /usr/include/sys/types.h \
  /usr/include/sys/endian.h /usr/include/sys/_endian.h \
  /usr/include/machine/endian.h /usr/include/sys/unistd.h \
  /usr/include/stdlib.h /usr/include/stdio.h /usr/include/errno.h \
  /usr/include/sys/errno.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/ctype.h /usr/include/sys/ioctl.h /usr/include/sys/filio.h \
  /usr/include/sys/sockio.h ../linenoise/linenoise.h
linenoise.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS} -c linenoise.c -o linenoise.lo

linenoise.asan.lo: linenoise.c ../linenoise/linenoise.c /usr/include/termios.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/ttycom.h /usr/include/sys/ioccom.h \
  /usr/include/sys/ttydefaults.h /usr/include/unistd.h \
  /usr/include/sys/_null.h /usr/include/sys/types.h \
  /usr/include/sys/endian.h /usr/include/sys/_endian.h \
  /usr/include/machine/endian.h /usr/include/sys/unistd.h \
  /usr/include/stdlib.h /usr/include/stdio.h /usr/include/errno.h \
  /usr/include/sys/errno.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/ctype.h /usr/include/sys/ioctl.h /usr/include/sys/filio.h \
  /usr/include/sys/sockio.h ../linenoise/linenoise.h
linenoise.asan.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_ASAN} -c linenoise.c -o linenoise.asan.lo

linenoise.debug.lo: linenoise.c ../linenoise/linenoise.c /usr/include/termios.h \
  /usr/include/sys/cdefs.h /usr/include/machine/cdefs.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/sys/ttycom.h /usr/include/sys/ioccom.h \
  /usr/include/sys/ttydefaults.h /usr/include/unistd.h \
  /usr/include/sys/_null.h /usr/include/sys/types.h \
  /usr/include/sys/endian.h /usr/include/sys/_endian.h \
  /usr/include/machine/endian.h /usr/include/sys/unistd.h \
  /usr/include/stdlib.h /usr/include/stdio.h /usr/include/errno.h \
  /usr/include/sys/errno.h /usr/include/string.h /usr/include/strings.h \
  /usr/include/ctype.h /usr/include/sys/ioctl.h /usr/include/sys/filio.h \
  /usr/include/sys/sockio.h ../linenoise/linenoise.h
linenoise.debug.lo: Makefile config.mk
	/usr/local/bin/libtool --tag=CC --mode=compile ${CC} ${CPPFLAGS} ${CFLAGS_DEBUG} -c linenoise.c -o linenoise.debug.lo
