/* kc3
 * Copyright from 2022 to 2026 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software granted the above
 * copyright notice and this permission paragraph are included in all
 * copies and substantial portions of this software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */
#ifndef LIBKC3_KC3_H
#define LIBKC3_KC3_H

#include "types.h"

#include "alist.h"
#include "alloc.h"
#include "arg.h"
#include "array.h"
#include "assert.h"
#include "block.h"
#include "bool.h"
#include "buf.h"
#include "buf_fd.h"
#include "buf_file.h"
#include "buf_inspect.h"
#include "buf_parse.h"
#include "buf_parse_s16.h"
#include "buf_parse_s32.h"
#include "buf_parse_s64.h"
#include "buf_parse_s8.h"
#include "buf_parse_sw.h"
#include "buf_parse_u16.h"
#include "buf_parse_u32.h"
#include "buf_parse_u64.h"
#include "buf_parse_u8.h"
#include "buf_parse_uw.h"
#include "buf_rw.h"
#include "buf_save.h"
#include "call.h"
#include "callable.h"
#include "ceiling.h"
#include "cfn.h"
#include "character.h"
#include "compare.h"
#include "data.h"
#include "do_block.h"
#include "endian.h"
#include "env.h"
#include "env_eval.h"
#include "error.h"
#include "eval.h"
#include "f32.h"
#include "f64.h"

#if HAVE_F80
# include "f80.h"
#endif

#if HAVE_F128
# include "f128.h"
#endif

#include "fact.h"
#include "facts.h"
#include "facts_cursor.h"
#include "facts_with.h"
#include "facts_with_cursor.h"
#include "fd.h"
#include "file.h"
#include "fn.h"
#include "fn_clause.h"
#include "frame.h"
#include "hash.h"
#include "ident.h"
#include "inspect.h"
#include "integer.h"
#include "io.h"
#include "kc3_main.h"
#include "list.h"
#include "map.h"
#include "marshall.h"
#include "marshall_read.h"
#include "module.h"
#include "ncpu.h"
#include "pcall.h"
#include "pcallable.h"
#include "pcomplex.h"
#include "pcow.h"
#include "plist.h"
#include "pointer.h"
#include "pretty.h"
#include "pstruct.h"
#include "pstruct_type.h"
#include "psym.h"
#include "ptag.h"
#include "ptr.h"
#include "ptr_free.h"
#include "pvar.h"
#include "quote.h"
#include "ratio.h"
#include "s16.h"
#include "s32.h"
#include "s64.h"
#include "s8.h"
#include "securelevel.h"
#include "sequence.h"
#include "sh.h"
#include "str.h"
#include "struct.h"
#include "struct_type.h"
#include "sw.h"
#include "sym.h"
#include "tag.h"
#include "time.h"
#include "timespec.h"
#include "tuple.h"
#include "u16.h"
#include "u32.h"
#include "u64.h"
#include "u8.h"
#include "ucd.h"
#include "unquote.h"
#include "uw.h"
#include "var.h"
#include "void.h"

#endif /* LIBKC3_KC3_H */
