## kc3
## Copyright from 2022 to 2026 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

build:

all:
	${MAKE} build
	${MAKE} debug

fuse:
#	${MAKE} -C fuse

fuse_asan:
#	${MAKE} -C fuse asan

clean::
#	${MAKE} -C fuse clean

clean_cov::
#	${MAKE} -C fuse clean_cov

cov:
#	${MAKE} -C fuse cov

debug:
#	${MAKE} -C fuse debug

distclean::
#	${MAKE} -C fuse distclean

gcovr:
#	${MAKE} -C fuse gcovr

install:
#	${MAKE} -C fuse install

uninstall:
#	${MAKE} -C fuse uninstall

.PHONY: \
	all \
	asan \
	clean \
	clean_cov \
	cov \
	debug \
	distclean \
	fuse \
	install \
	uninstall
