# sources.mk generated by update_sources
HEADERS = \
	"application.h" \
	"application_window.h" \
	"kc3_glib.h" \
	"kc3_gtk4.h" \
	"paned.h" \
	"types.h" \
	"window.h" \

SOURCES = \
	"application.c" \
	"application_window.c" \
	"kc3_glib.c" \
	"paned.c" \
	"window.c" \

