# sources.sh generated by update_sources
HEADERS='application.h application_window.h box.h button.h entry_buffer.h frame.h kc3_glib.h kc3_gtk4.h label.h list_box.h paned.h scrolled_window.h text.h text_view.h types.h widget.h window.h '
SOURCES='application.c application_window.c box.c button.c entry_buffer.c frame.c kc3_glib.c label.c list_box.c paned.c scrolled_window.c text.c text_view.c widget.c window.c '
