# sources.mk generated by update_sources
HEADERS = \
	"buf_linenoise.h" \
	"buf_wineditline.h" \

SOURCES = \
	"ikc3.c" \
	"ikc3_kc3s.c" \
	"kc3s.c" \

SOURCES_LINENOISE = \
	"buf_linenoise.c" \
	"linenoise.c" \

SOURCES_WINEDITLINE = \
	"buf_wineditline.c" \

