# sources.mk generated by update_sources
HEADERS = \
	"gl.h" \
	"gl_camera.h" \
	"gl_cylinder.h" \
	"gl_sphere.h" \
	"sdl2_font.h" \
	"sdl2_sprite.h" \
	"types.h" \
	"window_sdl2.h" \

SOURCES = \
	"gl.c" \
	"gl_camera.c" \
	"gl_cylinder.c" \
	"gl_sphere.c" \
	"sdl2_font.c" \
	"sdl2_sprite.c" \
	"window_sdl2.c" \

