## kc3
## Copyright from 2022 to 2026 kmx.io <contact@kmx.io>
##
## Permission is hereby granted to use this software granted the above
## copyright notice and this permission paragraph are included in all
## copies and substantial portions of this software.
##
## THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
## PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
## AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
## THIS SOFTWARE.

all:
	${MAKE} -C primehash64 all

asan:
	${MAKE} -C primehash64 asan

build:
	${MAKE} -C primehash64 build

clean:
	${MAKE} -C primehash64 clean

clean_cov:
	${MAKE} -C primehash64 clean_cov

cov:
	${MAKE} -C primehash64 cov

debug:
	${MAKE} -C primehash64 debug

distclean:
	${MAKE} -C primehash64 distclean

gcovr:
	${MAKE} -C primehash64 gcovr

install:
	${MAKE} -C primehash64 install

uninstall:
	${MAKE} -C primehash64 uninstall

.PHONY: all asan build clean clean_cov cov debug distclean gcovr install uninstall
