# sources.mk generated by update_sources
HEADERS = \
	"bg_rect.h" \
	"demo.h" \
	"earth.h" \
	"flies.h" \
	"lightspeed.h" \
	"mandelbrot_f128.h" \
	"matrix.h" \
	"toasters.h" \
	"types.h" \

SOURCES = \
	"bg_rect.c" \
	"demo.c" \
	"earth.c" \
	"flies.c" \
	"lightspeed.c" \
	"mandelbrot_f128.c" \
	"matrix.c" \
	"toasters.c" \

