# sources.mk generated by update_sources
HEADERS = \
	"bg_rect.h" \
	"demo.h" \
	"earth.h" \
	"flies.h" \
	"lightspeed.h" \
	"mandelbrot_f64.h" \
	"mandelbrot_f80.h" \
	"matrix.h" \
	"player.h" \
	"toasters.h" \
	"types.h" \

SOURCES = \
	"bg_rect.c" \
	"demo.c" \
	"earth.c" \
	"flies.c" \
	"lightspeed.c" \
	"mandelbrot_f64.c" \
	"mandelbrot_f80.c" \
	"matrix.c" \
	"player.c" \
	"toasters.c" \

