# sources.mk generated by update_sources
HEADERS = \
	"cairo_font.h" \
	"cairo_sprite.h" \
	"cairo_text.h" \
	"types.h" \
	"window_cairo.h" \

SOURCES = \
	"cairo_font.c" \
	"cairo_sprite.c" \
	"cairo_text.c" \
	"window_cairo.c" \

