# sources.mk generated by update_sources
HEADERS = \
	"gl_box.h" \
	"gl_camera.h" \
	"gl_cylinder.h" \
	"gl_deprecated.h" \
	"gl_font.h" \
	"gl_lines.h" \
	"gl_object.h" \
	"gl_ortho.h" \
	"gl_sphere.h" \
	"gl_sprite.h" \
	"gl_square.h" \
	"gl_text.h" \
	"gl_triangle.h" \
	"gl_vertex.h" \
	"gl_vtext.h" \
	"mat4.h" \
	"types.h" \
	"vec3.h" \

SOURCES = \
	"gl_box.c" \
	"gl_camera.c" \
	"gl_cylinder.c" \
	"gl_deprecated.c" \
	"gl_font.c" \
	"gl_lines.c" \
	"gl_object.c" \
	"gl_ortho.c" \
	"gl_sphere.c" \
	"gl_sprite.c" \
	"gl_square.c" \
	"gl_text.c" \
	"gl_triangle.c" \
	"gl_vertex.c" \
	"gl_vtext.c" \
	"mat4.c" \
	"vec3.c" \

