# sources.mk generated by update_sources
HEADERS = \
	custom_cairo_view.h \

SOURCES = \
	 \

OBJC_SOURCES = \
	custom_cairo_view.m \

SWIFT_SOURCES = \
	content_view.swift \
	custom_cairo_swiftui_view.swift \

